name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
        
      - name: Make gradlew executable
        run: sudo chmod +x gradlew

      - name: Build and Package
        run: ./gradlew build -x test

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/libs/fostersestate-api-1.0.0-SNAPSHOT.jar"
          target: "/home/ubuntu/"

      - name: Generate and Print Host Key Fingerprint
        run: |
          ssh-keygen -R ${{ secrets.EC2_HOST }} || true
          mkdir -p .ssh
          ssh-keyscan ${{ secrets.EC2_HOST }} >> .ssh/known_hosts
          ssh-keygen -lf .ssh/known_hosts

      

      - name: Run SSH command
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            sudo systemctl stop fostersestate-api.service
            sudo rm -rf /home/ubuntu/fostersestate-api-1.0.0-SNAPSHOT.jar
            sudo mv /home/ubuntu/fostersestate-api-1.0.0-SNAPSHOT.jar /home/ubuntu/fostersestate-api.jar
            sudo systemctl start fostersestate-api.service

        
