name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
        
      - name: Make gradlew executable
        run: sudo chmod +x gradlew

      - name: Build and Package
        run: ./gradlew build -x test

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/libs/fostersestate-api-1.0.0-SNAPSHOT.jar"
          target: "/home/ubuntu/"

      - name: Generate and Print Host Key Fingerprint
        run: |
          ssh-keygen -R ${{ secrets.EC2_HOST }} || true
          sudo mkdir -p /home/ubuntu/.ssh/
          sudo chown -R ubuntu:ubuntu /home/ubuntu/.ssh/
          ssh-keyscan ${{ secrets.EC2_HOST }} >> "/home/ubuntu/.ssh/known_hosts"
          ssh-keygen -lf "/home/ubuntu/.ssh/known_hosts"
      

      - name: Run SSH command
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i "private_key.pem" ubuntu@ec2-54-215-99-68.us-west-1.compute.amazonaws.com 'sudo systemctl restart fostersestate-api'
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USER }}


        
