name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: PWD
        run: |
          pwd
          ls -la

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
        
      - name: Make gradlew executable
        run: sudo chmod +x gradlew

      - name: Build and Package
        run: ./gradlew build -x test

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/libs/fostersestate-api-1.0.0-SNAPSHOT.jar"
          target: "/home/ubuntu/"

      - name: Generate and Print Host Key Fingerprint
        run: |
          cd /home/runner
          ls -la
          mkdir -p /home/runner/.ssh/
          touch /home/runner/.ssh/known_hosts
          ssh-keygen -R ${{ secrets.EC2_HOST }} || true
          ssh-keyscan ${{ secrets.EC2_HOST }} >> /home/runner/.ssh/known_hosts
          ssh-keygen -lf /home/runner/.ssh/known_hosts
          cat /home/runner/.ssh/known_hosts

      - name: Run SSH command
        run: |
          pwd
          echo "$PRIVATE_KEY" > /home/runner/.ssh/private_key.pem
          chmod 600 /home/runner/.ssh/private_key.pem
          ssh -i /home/runner/.ssh/private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo systemctl restart fostersestate-api.service"
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USER }}


        
